language: node_js

sudo: false

node_js:
  - '8'

branches:
  only:
    - master

# cache:
#   directories:
#     - node_modules

before_install:
  - openssl aes-256-cbc -K $encrypted_45cf3748e65b_key -iv $encrypted_45cf3748e65b_iv -in .travis/id_rsa_travis.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  - git config --global user.name islittlecat
  - git config --global user.email 738826716@qq.com

install:
  - npm install hexo-cli -g
  - npm install

script:
  - npm run deploy